export const ACTIONS = {

    SEARCH_PRODUCTS: "SEARCH_PRODUCTS",

    SHOW_FEATURED: "SHOW_FEATURED",

    TRACK_ORDER: "TRACK_ORDER",

    SIZE_GUIDE: "SIZE_GUIDE",

    RECOMMEND: "RECOMMEND",

    VIEW_CART: "VIEW_CART",

    VIEW_WISHLIST: "VIEW_WISHLIST",

    GENERAL: "GENERAL"

};